Entrega del header de la página
jojacomu/hoteles pull request #1
Opened 2023-07-27 05:40 UTC by jojacomu

Configuración de html básico y el header de la página, sin comportamientos funcionales de los filtros.

2023-07-27 14:13 UTC, DanielCalleCO requested changes

2023-07-27 14:13 UTC, DanielCalleCO commented on hoteles.html
En la linea 7 podrías quitar el / antes de `hoteles-style.css` por favor?

2023-07-27 14:15 UTC, DanielCalleCO commented
Haz el cambio en la linea 7 y aprobamos, está muy bonito tu header. Bien hecho!

2023-07-27 14:17 UTC, DanielCalleCO commented
recuerda resolver los conflicots también antes de hacer push
`git pull origin main`

2023-07-27 15:33 UTC, jojacomu reviewed
Done

2023-07-27 15:33 UTC, jojacomu commented on hoteles.html
Gracias por el feedback, done!

2023-07-28 21:47 UTC, DanielCalleCO commented
John, así está bien... PERO no debería darle uno click para que aparezcan las cards... deberían aparecer por default. Cambia eso y aprobamos

2023-07-28 21:47 UTC, DanielCalleCO requested changes
Haz aue aparezcan primero los hoteles, apenas entro a la página

2023-07-31 14:39 UTC, DanielCalleCO approved these changes

2023-08-01 02:13 UTC, merged