John c/hoteles cards
jojacomu/hoteles pull request #2
Opened 2023-08-14 16:39 UTC by jojacomu

Hola @DanielCalleCO, he estado ausente de solicitar tu ayuda por que la verdad inicie labores y me ha quedado difícil coordinar horario para buscar tu ayuda, no obstante me he apoyado en los compañeros para ir avanzando. En esta entrega mejoré estilos de las tarjetas y activé los filtros de país, fechas y precios.

Quedo atento a indicaciones. Shalom y bendiciones.

2023-08-14 17:24 UTC, DanielCalleCO requested changes
Podrías hacer el cambio en el boton clear?

2023-08-14 17:24 UTC, DanielCalleCO commented on src/hoteles.js
> +buttonConsulta.addEventListener("click", async () => {
Efectivamente el botón me muestra todos los hoteles, PERO no me está borrando los filtros, si tengo selecionado Chile, me muestra los hoteles de Chile, bien. Doy click en el botn CLEAR y me muestra todos los hoteles, bien... PERO me queda aún seleccionado Chile en el filtro de paises y así con todos, debería mostrarme los valores iniciales que se muestran al cargar la página

2023-08-14 22:02 UTC, jojacomu commented on src/hoteles.js
> +buttonConsulta.addEventListener("click", async () => {
Gracias @DanielCalleCO, cambios efectuados agregando instrucciones desde la línea 334 en adelante.

2023-08-15 00:07 UTC, DanielCalleCO commented
Hay algo en tu lógica que no está funcionando como debería, revisa por favor tu slack y me dices si lo puedes arreglar

2023-08-15 11:49 UTC, DanielCalleCO requested changes
Si selecciono la disponibilidad máxima (15 días) en el filtro de fechas, y selecciono en prices "$" me sobreescribe las fechas, osea, me muestra los hoteles con precio $ pero de todas las disponibilidades de fecha, lo que no tiene sentido... deben sumarse los filtros, no sobreescribirse. Revisalo por fa

2023-08-15 16:18 UTC, DanielCalleCO approved these changes

2023-08-15 16:21 UTC, merged